import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css"; 
import { getServerSession } from "next-auth";
import SignInButton from "@/components/custom/Signinbutton";
import  { Toaster } from 'react-hot-toast';
import { authOptions } from "@/lib/auth";
 
const inter = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "ONLY Code",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster />
      {/* <QueryClientProvider client={queryClient}> */}
       
        {session ? <>{children}</> : <SignInButton />}
    {/* </QueryClientProvider> */}
      </body>
    </html>
  );
}
